### ISSUE TITLE
Would LOVE to use it on my T9 Rockchip3328 TVBox

### ISSUE THREAD

**Issue by BoscoMoney** [retro-center/rcade_releases#10]
Model: T9
Type: TV Box
GPU: Mali-450MP2
System: Android 8.1
CPU: RK3328
Core: Cortex A53,Quad Core
RAM: 4G
RAM Type: DDR3
ROM: 32G
Any chance you can make this happen? Thanks.

**Comment by retro-center** [comment]
Thanks for reaching out! I don't have this device to test with, so I wouldn't be able to reliably make it work. But if you reach out to me on discord then we can discuss future options of having you test this hardware and I can send you some experimental builds
