### ISSUE TITLE
Keyboard Mappings should be in readme

### ISSUE THREAD

**Issue by bigchipbag** [retro-center/rcade_releases#11]
I really enjoy the R-Cade program, it's the perfect "set and forget" for the Rock64!

I believe that the default keyboard settings should be put somewhere in the readme, the controls were not intuitive on first use and took a lot of trial and error getting set up without a gamepad or anything.

Enter as "Menu" is okay
A is "back", S is "select" etc. not immediately intuitive.

It's a bit easier to use once you get into Kodi, but even kodi without a mouse or pad is a a bit tough (e.g. setting up an SMB share, the arrow keys don't go to the right to hit "OK" - you have to intuit that you need to hold down Control (or was it Shift?))

**Comment by retro-center** [comment]
Latest Release allows users to view current mappings under input profiles :) Thank you for the feedback!!
