### ISSUE TITLE
Framerate issues on RockPro64

### ISSUE THREAD

**Issue by mntn-xyz** [retro-center/rcade_releases#16]
This is an issue with every system. It feels like the framerate is just slightly off, as there is no lag, but scrolling stutters a bit and fast blinking objects don't render properly. I have used LibreELEC/Kodi with a Rock64 on the same TV without issues. I've explored the settings and I don't see any framerate options. Help with debugging further would be appreciated.

**Comment by retro-center** [comment]
Thank you for reporting! Yes this is an SDL related issue and is fixed in this upcoming release 

>

**Comment by mntn-xyz** [comment]
Fantastic, glad to hear it!

**Comment by mntn-xyz** [comment]
Fixed in latest release
