### ISSUE TITLE
Accessing ROMs held on SATA drive

### ISSUE THREAD

**Issue by mntn-xyz** [retro-center/rcade_releases#17]
I'm using a RockPro64 with the Roshambo case, and I'm having trouble accessing ROMs stored on the SATA "cartridge". I formatted the cartridge as FAT32 in Linux and copied over the directory structure that Rcade creates from an external USB drive. I also dropped some ROMs into the proper folders on the drive. Unfortunately it seems like Rcade isn't detecting those ROMs. How can I determine what the issue is? Thanks!

**Comment by mntn-xyz** [comment]
I think this is a hardware issue (power) based on some forum posts I read. It worked on one boot but then the USB controllers disconnected at random.

**Comment by knopancakes** [comment]
I found my cartridge fails to read if plugged in at boot, but if plugged in after splash screen it works fine.
Did do you have more information on the hardware issue? I couldn't find the forum posts you referenced.
