### ISSUE TITLE
unable to launch games from external storage

### ISSUE THREAD

**Issue by robbdi** [retro-center/rcade_releases#18]
I have copied over the correct game(s) and bios for the system I want to play. If I run a game from local storage, it runs. If I run the game from external storage (usb0), I am met with the message "The game appears to have failed to start correctly. This can be due to a missing BIOS or PAK files or an invalid ROM."

Any suggestions?

**Comment by retro-center** [comment]
Thank you for reaching out!

Please confirm if this issue still exists on v1.0.8. If so, can you please enable debug logging, reboot, and generate a support archive from the new support menu and send it over for my review?

**Comment by retro-center** [comment]
Closing due to no response and new released 1.0.9
