### ISSUE TITLE
It works with  RK3399 ?

### ISSUE THREAD

**Issue by jocieldo** [retro-center/rcade_releases#2]
It works with  RK3399 ?

Just a question. Thank you for your amazing work!!!

**Comment by mrfixit2001** [comment]
Hello! RK3399 does not yet have a release, but it WILL soon :) So yes, it will work VERY well on RK3399, but I have not yet uploaded a release for it yet.

**Comment by jocieldo** [comment]
> Hello! RK3399 does not yet have a release, but it WILL soon :) So yes, it will work VERY well on RK3399, but I have not yet uploaded a release for it yet.

Thank you so much, man. Looking forward to it.

**Comment by retro-center** [comment]
RK3399 support added in v1.0.5 release! Additional uploads still pending :) GAME ON!
