### ISSUE TITLE
C button not mapping to R1 on Quad Play in PS1 emulator

### ISSUE THREAD

**Issue by TheHyeOne** [retro-center/rcade_releases#22]
**Describe the bug**
When button mapping in PS1 emulator, the C button should be R1, but is not, will not correctly map

**To Reproduce**
Play Street Fighter EX 2 PS1, then while in game, go to controls and you can press each button to map it directly, C is just empty, Z works fine as L1

**Expected behavior**
See above 

**Screenshots**
![20230127_231043](https://user-images.githubusercontent.com/2909100/215289879-69b9c9e4-a7ec-4171-bb6b-3b5de43c2ebd.jpg)

**Environment (please complete the following information):**
ALU 1.2 (on newest FW)
Quad Play (on newest FW)

**Additional context**

**Comment by TheHyeOne** [comment]
Just an update, i did end up adding the PS1 bios, and im not sure if that worked, or i just needed a reboot, but it now maps 100% properly.

**Comment by retro-center** [comment]
I’m glad you’re all set! Thanks for reporting!
