### ISSUE TITLE
Rcade stuck at "System Starting" screen too often (from 10 boots it stuck on 6 of them)

### ISSUE THREAD

**Issue by wlcina** [retro-center/rcade_releases#24]
**Describe the bug**
Upon turning on ALU, Rcade stuck at "system starting" screen - more than half of boots. If I turn off and turn on ALU, then it boots correctly. I waited 15 minutes - system was still stuck.
I noticed holding P2 during stucked system it light up blue diods - so system seems to be not completely frozen.

**To Reproduce**
Turn on the system. Like I said is pretty random if it stuck.

**Expected behavior**
System boots to Rcade

**Environment (please complete the following information):**
 - R-Cade Version: 1.0.8
 - Board ALU 1.1 (I believe)
 - Sandisk 256GB
 - BitLCD
 - recommended Sabrent USB hub

**Comment by retro-center** [comment]
Can you please let me know if upgrading to 1.0.9 and then reinstalling Legends Unchained UCE from your stock firmware resolves this?
Thank you for reporting it!

**Comment by jonmagee** [comment]
I'm experiencing this as well still, and I did go and re-install LU and upgrade to 1.0.9.

**Comment by MetlarKnight** [comment]
I have the same problem. Seems to be a lot of people experiencing this issue.

**Comment by retro-center** [comment]
Thank you for opening this issue. It was a long-standing randomly occurring issue and we believe we have resolved in this latest release v2.0.3. Please let me know if you continue to experience this.
