### ISSUE TITLE
Make /usr/bin/gaterestrictor customizable

### ISSUE THREAD

**Issue by miwasp** [retro-center/rcade_releases#26]
**Describe the solution you'd like**
/usr/bin/gaterestrictor is a compiled executable in which 4-way games are hardcoded. It would be nice if this can be made customizable.

**Additional context**
At least "dkongjp" is missing. Can you please add it?

**Comment by n-i-x** [comment]
dkongjp was added in https://github.com/ACustomArcade/tos428/commit/efe9dcae0b259df15b24d3cc5a3dbeae11ab8867

**Comment by n-i-x** [comment]
Support for custom roms lists has been added in https://github.com/ACustomArcade/tos428/commit/9ec8782e570aa6571dcfa9b5c2ff96d2c5307386

**Comment by retro-center** [comment]
Support for adding any game to your collection to the gate restrictor has now been added to v1.1.1 :)
