### ISSUE TITLE
Many mame games are displayed with rom name instead of game name

### ISSUE THREAD

**Issue by miwasp** [retro-center/rcade_releases#27]
**Describe the bug**
I uploaded a full mame2003-plus set (freshly generated with clrmamepro based on a xml created in RA on LU).
If you don't have any name-tags in your gamelist.xml, Emulationstation normally displays the name of the game.
For many games the romname is displayed instead.

**To Reproduce**
1. Upload full set of mame2003-plus into mame folder
2. Scrape to generate a gamelist.xml
3. Delete all name-tags in gamelist.xml (if your scraper generated them)
4. Restart ES
5. Many games are displayed with romname (for example dkongjp and choplftr)

**Expected behavior**
All games should display the game name instead of the romname

**Environment (please complete the following information):**
 - R-Cade Version: 1.0.8
 - Board Atgames Legend Ultimate 1.1

**Additional context**
This can be solved if you update "/rcade/share/.emulationstation/resources/mamenames.xml" with a newer version, for example
this one: https://raw.githubusercontent.com/RetroPie/EmulationStation/master/resources/mamenames.xml

**Comment by retro-center** [comment]
Thank you for this insight! This update will be included in the next release!

**Comment by retro-center** [comment]
All updated in 1.0.9!
