### ISSUE TITLE
System Boot Failure on RockPi 4C +

### ISSUE THREAD

**Issue by colder1989** [retro-center/rcade_releases#30]
I have flash image on my RockPi 4C+ but i have System Boot Failure and no partition created. It's possible to make it compatible? it's hard to add Rockpi 4 c+ DTB? please. thanks

**Comment by CAPSBOY** [comment]
hi have the same problem, is there a 1.1.0 build available for the RockPi 4C+

Thanks

**Comment by CAPSBOY** [comment]
bump 1.10 still no luck

**Comment by mikerocklewitz** [comment]
I have this issue on rock64.  Cant boot.  I hooked up serial terminal and its failing to mount or see rootfs.  I could get a full printout if it helps but I think its something to do with the way the microsd is being partitioned from the image.....

**Comment by retro-center** [comment]
> I have this issue on rock64. Cant boot. I hooked up serial terminal and its failing to mount or see rootfs. I could get a full printout if it helps but I think its something to do with the way the microsd is being partitioned from the image.....

The RockPi4C issue is different than this. Thank you greatly for opening the other issue, please see my response regarding your board using a different uboot. 

@CAPSBOY my apologies about not responding sooner... I believe we spoke about this in discord, or perhaps it was another user with the same question. But yes, I don't have the RockPi4C board to test with, so at this time R-Cade is only able to boot the 4B and not the 4C. This should be a simple device tree difference however, and I should be able to add this board by comparing the different DTS files. If you're on discord, please ping me so I can send you some test files.

**Comment by CAPSBOY** [comment]
ill jump back in there and have a chat with y as I'm still getting the
dosbox-svn error when trying to compile for the 4c Plus.

Cheers

**Comment by retro-center** [comment]
The new release v2.0.3 is now available and has specific builds all the different Rockpi4 models. Be sure you download the right one for the board you want to use. Game on!
