### ISSUE TITLE
Choose custom video directory for screensaver

### ISSUE THREAD

**Issue by kniq86** [retro-center/rcade_releases#32]
**Describe the solution you'd like**
I would like to be able to choose specific videos or at least a designated folder of videos for the screensaver. The game clips are cool, but many of the videos don't  work and just load a black screen.

**Describe alternatives you've considered**
The image slideshow screensaver has a menu option for choosing a specific folder. Give us the same thing for the video screensaver please!

**Comment by retro-center** [comment]
This is a great feature request, thank you! Will work to include this in a future release :)

**Comment by retro-center** [comment]
A ton of new features have been added in v2.0.3, including this. Thank you so much for your feedback!
