### ISSUE TITLE
Option for separate Video Screensaver audio

### ISSUE THREAD

**Issue by Mobeeuz** [retro-center/rcade_releases#33]
I would like to see the video screensaver audio toggle work independently. As it stands, the system settings disables both. I would rather have video audio during the screensaver, but not while browsing.

**Comment by retro-center** [comment]
Thanks for reaching out! V1.1.1 release adds this option :) you can adjust the gamelist and screensaver volume separately from the background music, and you can also enable / disable the audio for the gamelist and screensaver. It’s all available under audio settings. 
GAME ON!

**Comment by Mobeeuz** [comment]
Despite my efforts I was unclear. I'm looking for gamelist video audio to
be disabled while browsing, but enabled during the screensaver. Right now
the gamelist volume controls both, as does disabling gamelist video audio.
Background music has nothing to do with it.

**Comment by retro-center** [comment]
Thanks for pointing this out! That’s a bug, when sceeensaver audio is not muted the sound should be enabled. It will be resolved in the next release.

**Comment by retro-center** [comment]
This is resolved in v2.0.3, thank you for reporting this!
