### ISSUE TITLE
Wifi incredible slow 

### ISSUE THREAD

**Issue by jh1982** [retro-center/rcade_releases#35]
The rockpro64 connects to the wifi, but it`s incredible slow. Even to slow for putty.

 - R-Cade Version: 1.1.1
 - Board Pine rockpro64
 - OS Disk emmc

**Comment by bstone108** [comment]
this is probably due to the older kernel included with rcade.  From my understanding this will probably go away next version as a newer kernel is being added to the next release. Only testing will tell once new version is ready to be tested.

**Comment by jh1982** [comment]
> The latest release v2.0.3 should resolve, and is available for download and upgrade now. If you encounter any related issues, please let me know.

After the update, I get system boot failure from emmc.
Boot from sd card works just fine.
![Uploading 20241031_205207.jpg…]()
