### ISSUE TITLE
WiFi passwords with special characters don't connect

### ISSUE THREAD

**Issue by hot-steamer** [retro-center/rcade_releases#36]
**Describe the bug**
Connecting to a WiFi network that contains a '!' or other special character in the password does not work.  Dumping a support archive shows the password is being stored in the wpa_supplicant.conf file in plain ASCII text which has known issues with special characters.

**To Reproduce**
1. Configure a wifi network with a '!' in the password
2. Attempt to connect to the network by setting the details in the network menu
3. Observe no error messages and the wireless remains disconnected
4. Dump the support archive and observe the wpa_supplicant.conf file has the password verbatim including special characters that will cause issues.

**Expected behavior**
A wireless connection is established.

**Screenshots**
-none-

**Environment (please complete the following information):**
 - R-Cade Version: 1.1.1 (Linux version 4.4.302-mrfixit (mrfixit2001@mrfixit2001-VB))
 - Board: ha8801
 - OS Disk: ID 090c:1000 Silicon Motion, Inc. - Taiwan (Samsung Flash Drive FIT)

**Additional context**
Converting the password to an unquoted hex string may be the easier solution:
https://web.mit.edu/freebsd/head/contrib/wpa/wpa_supplicant/wpa_supplicant.conf

**Comment by retro-center** [comment]
Thank you for the detailed report!

I can confirm that PSK's with an exclamation point DO currently work, I just checked it in a lab environment, but your suggestion about converting the value to hex is an excellent idea and we will definitely investigate that path. Thanks again!

**Comment by hot-steamer** [comment]
I may have zero'd in on the wrong character. I have two wireless networks, neither worked and the common character was a '!' character. I did test the wifi with a hotspot that does have a pretty plain password and that worked. Other special characters that are in those two passwords are: !#@'

Would you mind trying the apostrophe and pound in your test next?

Though if the change will happen either way, it is a bit moot. But I would like to connect it to the wifi without removing the other special characters.

**Comment by retro-center** [comment]
Closing now that v2.0.3 is out for all boards, but please let me know if there's any related concerns so I can address them.
