### ISSUE TITLE
Access controller reorder in kiosk mode

### ISSUE THREAD

**Issue by chadbanks** [retro-center/rcade_releases#40]
I would like the ability to reorder external bluetooth controllers while in kiosk mode. It can be done when not in kiosk mode. But I want users to be able to change the order when the device is in kiosk mode. Because I want users to be able to connect an external controlelr to play NES games for example, and then change it to be the first controller so they can play the game with the controller. They're unable to do this in kiosk mode.

**Comment by n-i-x** [comment]
Thanks for the feature request. Unfortunately, this is highly specific to your use cases and not something we'd likely implement.

At some point, we may decide to make settings more fine-grained for Kid and/or Kiosk mode but it's not a high priority at this point in time.

**Comment by retro-center** [comment]
@chadbanks as stated, the settings are locked down in kiosk mode for a reason and making them accessible is not considered "secure" and would lead to unexpected behavior.

That being said, I've added this to our backlog: "optionally player starting game is player 1"
This won't be implemented right away, and when it is it will be disabled by default. 
But, when enabled, starting a game using using the player 2 controls would change that player to be player 1.
