### ISSUE TITLE
WiFi password is clearly visible and not masked

### ISSUE THREAD

**Issue by chadbanks** [retro-center/rcade_releases#41]
Will you please mask the wifi password in the security section so that users cannot see the password? Thanks.

**Comment by retro-center** [comment]
@chadbanks thanks for the feature request! This was already brought up in issue #36. The wifi password uses custom encryption in RCade settings itself, but when the wireless is actually setup then the password is currently stored as plain text in the config file. This fix is ready and will be included in the next release :)
