### ISSUE TITLE
Pinebook Pro fails to launch any game

### ISSUE THREAD

**Issue by mattjb1222** [retro-center/rcade_releases#42]
**Description of problem**
No games launch, aside from Wolf3D (MSDOS).

**Steps to reproduce the behavior:**
New installation of 1.1.1 - accepted License agreement, but Wi-Fi cannot be connected yet at this point.
Connected Wi-Fi.
Factory Reset Rcade via Support Menu.
Accepted License agreement (this time Wi-Fi was connected as it seems wpa_supplicant.conf information persists past Factory Reset).
Try to launch any game (specifically SNES: Mega Family Bros in the output below.

**Environment (please complete the following information):**
 - R-Cade Version: 1.1.1
 - Board: Pinebook Pro

**Additional context**
`
Jun 06 19:15:53 lvl3:   UIModeController::logInput( Keyboard ):Key S[168], isMappedTo= b, , value=0
Jun 06 19:15:54 lvl3:   UIModeController::logInput( Keyboard ):Key S[168], isMappedTo= b, , value=1
Jun 06 19:15:54 lvl2:    req sound [detailed.launch]
Jun 06 19:15:54 lvl2:      (missing)
Jun 06 19:15:55 lvl2:   Attempting to launch game...
Jun 06 19:15:55 lvl3:   De-Initializing Input Manager
Jun 06 19:15:55 lvl3:   Initializing Input Manager
Jun 06 19:15:55 lvl2:   De-Initializing Audio Manager...

Jun 06 19:15:56 lvl3:   De-Initializing Input Manager
Jun 06 19:15:56 lvl3:   De-initializing Windowing System
Jun 06 19:15:57 lvl3:   Scripting: killing thread with handle 7
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 1
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 2
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 3
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 4
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 5
Jun 06 19:15:57 lvl3:   Killing textureloader thread with handle 6
Jun 06 19:15:57 lvl3:   Running System Command: rm -f /tmp/*.resolution
Jun 06 19:15:57 lvl3:   Scripting: executing: /rcade/scripts/es_scripts/game-start/01-gaterestrictor.sh "/rcade/share/roms/snes/megafamilybros.smc" "megafamilybros" "MEGA FAMILY BROS"
Jun 06 19:15:57 lvl3:   ThreadFactory: Killing all threads
Jun 06 19:15:57 lvl2:           /rcade/scripts/launcher.py --system snes --emu lr-snes9x2005 --joytype "" --rom /rcade/share/roms/snes/megafamilybros.smc --p1 "[0,0,-1,0,120,0,DEFAULT,Keyboard]"
Jun 06 19:15:57 lvl3:   Running System Command: /rcade/scripts/launcher.py --system snes --emu lr-snes9x2005 --joytype "" --rom /rcade/share/roms/snes/megafamilybros.smc --p1 "[0,0,-1,0,120,0,DEFAULT,Keyboard]"
Jun 06 19:15:57 lvl1:   ...launch terminated with nonzero exit code 256!
Jun 06 19:15:57 lvl2:   Creating window...
Jun 06 19:15:57 lvl3:   Identified kernel 4.4, initializing full graphics stack
Jun 06 19:15:57 lvl2:   DRM_SETRES REQUESTING RESOLUTION: 1920x1080
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 1920x1080
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 1024x768
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 800x600
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 800x600
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 848x480
Jun 06 19:15:57 lvl3:   drm_setres checking resolution: 640x480
Jun 06 19:15:57 lvl3:   drm_setres chose resolution: 1920x1080
Jun 06 19:15:57 lvl3:   Found encoder crtc
Jun 06 19:15:57 lvl3:   Using display 0xf7e7b0 with EGL version 1.4
Jun 06 19:15:57 lvl3:   EGL Version 1.4 Midgard-"r18p0-01rel0"
Jun 06 19:15:57 lvl3:   EGL Vendor ARM
Jun 06 19:15:57 lvl3:   EGL Extensions EGL_KHR_partial_update EGL_KHR_image_pixmap EGL_EXT_image_dma_buf_import EGL_KHR_config_attribs EGL_KHR_image EGL_KHR_image_base EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_KHR_get_all_proc_addresses EGL_IMG_context_priority EGL_ARM_pixmap_multisample_discard EGL_ARM_implicit_external_sync EGL_KHR_gl_texture_2D_image EGL_KHR_gl_renderbuffer_image EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_KHR_gl_texture_cubemap_image EGL_EXT_create_context_robustness
Jun 06 19:15:57 lvl3:   GL Extensions:GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex
Jun 06 19:15:57 lvl3:   Updating Screen Settings...
Jun 06 19:15:57 lvl2:   Created window successfully.
Jun 06 19:15:57 lvl2:   GL vendor:   ARM
Jun 06 19:15:57 lvl2:   GL renderer: Mali-T860
Jun 06 19:15:57 lvl2:   GL version:  OpenGL ES 3.2 v1.r18p0-01rel0.63a7b6d760afbc2677d0891cc09832cf
Jun 06 19:15:57 lvl2:   Checking available OpenGL extensions...
Jun 06 19:15:57 lvl2:    ARB_texture_non_power_of_two: MISSING
Jun 06 19:15:57 lvl3:   VSync with ReTrace Successfully Enabled
Jun 06 19:15:57 lvl3:   Initializing Input Manager
Jun 06 19:15:58 lvl2:   Clearing invalid controller Keyboard for Player 1
Jun 06 19:15:58 lvl3:   Starting textureloader thread #1
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 1(3822047552)
Jun 06 19:15:58 lvl3:   Starting textureloader thread #2
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 2(3813654848)
Jun 06 19:15:58 lvl3:   Starting textureloader thread #3
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 3(3805262144)
Jun 06 19:15:58 lvl3:   Starting textureloader thread #4
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 4(3796869440)
Jun 06 19:15:58 lvl3:   Starting textureloader thread #5
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 5(3788476736)
Jun 06 19:15:58 lvl3:   Starting textureloader thread #6
Jun 06 19:15:58 lvl3:   ThreadFactory: Successfully Created New Thread 6(3780084032)
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: :/ES-splash.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: :/scroll_gradient.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: :/frame.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: :/button.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: :/button.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/bg_with_shadow.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/steelcarousel.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/bg.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/gamelist.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/box.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/roms/mrboom/downloaded_images/mrboom-image.png
Jun 06 19:15:58 lvl3:   TextureData: Loading texture from file: /rcade/share/roms/snes/downloaded_images/megafam.jpg
Jun 06 19:15:58 lvl3:   Running RCade Command: /rcade/scripts/rcade-commands.sh audiocards
Jun 06 19:15:58 lvl2:   AudioOut: (0:0) es8316-spk-soun - es8316-spk-sound - ff890000.i2s-ES8316 HiFi ES8316 HiFi-0
Jun 06 19:15:58 lvl2:   Initializing card hw:0 on device Master
Jun 06 19:15:58 lvl3:   VolumeControl::init() - Opened ALSA mixer
Jun 06 19:15:58 lvl3:   VolumeControl::init() - Attached to default card
Jun 06 19:15:58 lvl3:   VolumeControl::init() - Registered simple element class
Jun 06 19:15:58 lvl3:   VolumeControl::init() - Loaded mixer elements
Jun 06 19:15:58 lvl3:   VolumeControl::init() - Mixer initialized
Jun 06 19:15:58 lvl2:   System Volume Changed to 76
Jun 06 19:15:58 lvl2:   Initializing Audio Manager...

Jun 06 19:15:59 lvl2:   Audio Manager Initialized

Jun 06 19:15:59 lvl3:   Loading Track /rcade/resources/systems/bgmusic/RCadeBGMusic.mp3
Jun 06 19:16:00 lvl2:   Resuming Music at 292.708

Jun 06 19:16:00 lvl3:   ThreadFactory: Successfully Created New Thread 7(3730104640)
Jun 06 19:16:00 lvl3:   Running System Command: /rcade/scripts/rcade-commands.sh cleantemp
Jun 06 19:16:00 lvl3:   ViewController::reloadGameListView
Jun 06 19:16:00 lvl3:   ViewController::getGameListView: snes
Jun 06 19:16:00 lvl3:   Restoring previous gamelist selection
Jun 06 19:16:00 lvl3:   Scripting: executing: /rcade/scripts/es_scripts/game-selected/01-bitlcd.sh "snes" "/rcade/share/roms/snes/megafamilybros.smc" "MEGA FAMILY BROS"
Jun 06 19:16:00 lvl3:   Scripting: executing: /rcade/scripts/es_scripts/game-selected/02-pixelweb.sh "snes" "/rcade/share/roms/snes/megafamilybros.smc" "MEGA FAMILY BROS"
Jun 06 19:16:00 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/top.png
Jun 06 19:16:00 lvl3:   TextureData: Loading texture from file: /rcade/share/.emulationstation/themes/rcade/assets/bottom.png
Jun 06 19:16:00 lvl3:   TextureData: Loading texture from file: :/button.png
Jun 06 19:16:00 lvl3:   TextureData: Loading texture from file: :/button_filled.png
Jun 06 19:16:00 lvl3:   TextureData: Loading texture from file: :/button_filled.png
`

**Comment by retro-center** [comment]
Please update to the latest release v2.0.3 as a *massive* amount of things have been fixed and let me know if the issue persists. If it does - please enable debug logging in the support menu and attach the generated support archive.

**Comment by retro-center** [comment]
Closing due to no response, Pinebook Pro is testing well for me. Please re-open if problem persists.
