### ISSUE TITLE
5.71 ALU new UI

### ISSUE THREAD

**Issue by Viper3881** [retro-center/rcade_releases#51]
**Describe the bug**

**To Reproduce**
1. Setup USB
2. Turn on ALU
3. Go to addon
4. Launch rcade

**Expected behavior**
Legends Unchained splash screen comes up but then goes right back to the main UI. Never get the 

option to backup or anything. Both OTG and External were purchased for 100 dollars to enable external devices.

**Screenshots**
[VIDEO OF LOOP](https://github.com/user-attachments/assets/7d7ed509-2d00-4d8c-855f-32f3f25bf649)

**Environment (please complete the following information):**
 - R-Cade Version: [e.g. 2.0.3}
 - Board RCade-Full-HA8801
 - OS Disk [USB drive]

**Comment by n-i-x** [comment]
Legends Unchained does not work on this firmware. You'll need to downgrade to 5.68.

**Comment by Viper3881** [comment]
Reports of possible bricking the device. I'd be cautious as no one can say if the lower F/W commonly available will run on this machine. Could brick it. ALP 4k in my debugging file. I guess makes sense based on the similarity now.

**Comment by n-i-x** [comment]
> Reports of possible bricking the device. I'd be cautious as no one can say if the lower F/W commonly available will run on this machine. Could brick it. ALP 4k in my debugging file. I guess makes sense based on the similarity now.

The hardware is identical as the previous ha8802 according to photos sent to me of the motherboard.
