### ISSUE TITLE
Frozen system

### ISSUE THREAD

**Issue by Christian-Gibbons** [retro-center/rcade_releases#52]
**Describe the bug**
After boot-up, the system locks up.  It is non-responsive to input, the background music stops, the status LED stops blinking, and the picture output freezes or sometimes goes blank.

**To Reproduce**
1. Power on device
2. wait a couple seconds after boot-up.

**Environment (please complete the following information):**
 - R-Cade Version: 2.0.4
 - Board: Rockbox

**Additional context**
Problem began immediately after updating from 2.0.3.

**Comment by Christian-Gibbons** [comment]
This issue persisted the many power cycles.  However, after leaving it unplugged for a couple days, it has since booted up and stayed on without incident.  I'm gonna go ahead and close.

**Comment by retro-center** [comment]
@Christian-Gibbons thank you for the follow up! Please do not hesitate to reach out directly if the problem resurfaces so we can get it resolved for you.
