### ISSUE TITLE
It works with Rock Pi 4？

### ISSUE THREAD

**Issue by WangONC** [retro-center/rcade_releases#9]
It works with Rock Pi 4？
I'm looking forward to it
Thank you for everything！

**Comment by tatujan** [comment]
Also Curious about this. Tried with RockPro64 image since they use the same chip. But can't get it to boot.

**Comment by retro-center** [comment]
Thanks for showing support and interest! I have not yet pushed a release for this board, but now that you’ve opened this issue - I absolutely will :)

>

**Comment by retro-center** [comment]
Latest release supports RockPi4 :)

**Comment by navyfighter12** [comment]
Which version of the Rock Pi 4 is supported? I have the Rock Pi 4 c+ and the image is not working. I will see if I can get any logs to assist in troubleshooting

**Comment by navyfighter12** [comment]
It says to check initrd.log located in the boot partition but there is no log. Any ideas? @retro-center

**Comment by retro-center** [comment]
@navyfighter12 R-Cade supports RockPi4B, the device tree used can be found here:
https://github.com/mrfixit2001/rockchip-kernel/blob/release-4.4/arch/arm64/boot/dts/rockchip/rk3399-rockpi-4b.dts

I don't have a RockPi4 model C to test with, unfortunately. 
Based on Radxa's device tree, it looks like model C does have hardware differences. I don't see anything that I would initially think would cause an issue, but these differences might possibly cause it not to boot properly. You can see differences listed here:
https://github.com/radxa/kernel/blob/release-4.4-rockpi4/arch/arm64/boot/dts/rockchip/rk3399-rock-pi-4c.dts

The initrd.log file would be on the boot partition. It can only be created if the system is able to properly boot the kernel and mount the partition, however. If you're not seeing a log file then it must not be getting that far in the boot process.

You could start by trying a different eMMC or SD card, or even trying to boot off a USB drive.

**Comment by NeuerUser** [comment]
I have a Rock Pi 4A with 2GB RAM. I gave the latest release file (1.0.7) a try. It started successfully, showed a screen with an arcade cabinet and several activities (e.g. "expanding filesystem" and so on) and then rebootet. After reboot the screen remained black (actually "no HDMI signal"), the blue LED flashed rapidly for some time and then stopped.

I took out the SD card and found the initrd.log file. It shows the following:

`Fri Jan 18 08:50:07 UTC 2013: Initrd script initialized... | | Fri Jan 18 08:50:07 UTC 2013: Detected identified boot device with: /dev/mmcblk0p1, trying to mount... | | Fri Jan 18 08:50:07 UTC 2013: Boot partition successfully located and mounted
Fri Jan 18 08:50:07 UTC 2013: Creating in-memory filesystem (tmpfs)...
Fri Jan 18 08:50:07 UTC 2013: Initializing the rootfs - mounting as writeable...
Fri Jan 18 08:50:07 UTC 2013: Initialization complete, making rootfs readonly...
Fri Jan 18 08:50:07 UTC 2013: Mounting the rootfs overlay...
Fri Jan 18 08:50:07 UTC 2013: System successfully initialized, preparing to boot rootfs...
`
That doesn't show very much, though. Apparently the boot from rootfs doesn't work, or it stops logging to initrd.log. Any idea?

**Comment by NeuerUser** [comment]
Addendum: After several more tries it now shows a screen. No idea, what changed, but there is a screen asking for a gamepad / controller. Now I need to read though the docs howto connect one. :-)

**Comment by jocieldo** [comment]
> Addendum: After several more tries it now shows a screen. No idea, what changed, but there is a screen asking for a gamepad / controller. Now I need to read though the docs howto connect one. :-)

What do you did to get this screens? I also got the same log...

Fri Jan 18 08:50:08 UTC 2013: Initrd script initialized... | | Fri Jan 18 08:50:08 UTC 2013: Detected identified boot device with: /dev/mmcblk0p1, trying to mount... | | Fri Jan 18 08:50:08 UTC 2013: Boot partition successfully located and mounted
Fri Jan 18 08:50:08 UTC 2013: Creating in-memory filesystem (tmpfs)...
Fri Jan 18 08:50:08 UTC 2013: Initializing the rootfs - mounting as writeable...
Fri Jan 18 08:50:08 UTC 2013: Initialization complete, making rootfs readonly...
Fri Jan 18 08:50:08 UTC 2013: Mounting the rootfs overlay...
Fri Jan 18 08:50:08 UTC 2013: System successfully initialized, preparing to boot rootfs...
